Repository cybercog/laravel-love, pull requests merged in 2019-09, with the labels that each got.

#110 Fix contract dependency from concrete implementation
  CHANGELOG.md
  contracts/Reactable/Exceptions/ReactableInvalid.php
  contracts/Reactant/Exceptions/ReactantInvalid.php
  contracts/Reactant/ReactionCounter/Exceptions/ReactionCounterDuplicate.php
  contracts/Reactant/ReactionCounter/Exceptions/ReactionCounterInvalid.php
  contracts/Reactant/ReactionTotal/Exceptions/ReactionTotalDuplicate.php
  contracts/Reactant/ReactionTotal/Exceptions/ReactionTotalInvalid.php
  contracts/Reacter/Exceptions/ReacterInvalid.php
  contracts/Reaction/Exceptions/RateOutOfRange.php
  contracts/ReactionType/Exceptions/ReactionTypeInvalid.php
  src/Reaction/Models/Reaction.php
Labels: bugfix, enhancement

#111 Fix Reacter model's hasReactedTo & hasNotReactedTo methods signature
  CHANGELOG.md
  contracts/Reacter/Models/Reacter.php
  src/Reacter/Models/NullReacter.php
  src/Reacter/Models/Reacter.php
Labels: enhancement

#113 Add Laravel v6 support
  .gitignore
  CHANGELOG.md
  composer.json
Labels: enhancement

#114 Add Laravel v6 support to Love v5
  .gitignore
  composer.json
  tests/TestCase.php
Labels: enhancement

#118 Fix custom connection in database migrations
  CHANGELOG.md
  database/migrations/2018_07_22_000100_create_love_reacters_table.php
  database/migrations/2018_07_22_001000_create_love_reactants_table.php
  database/migrations/2018_07_22_001500_create_love_reaction_types_table.php
  database/migrations/2018_07_22_002000_create_love_reactions_table.php
  database/migrations/2018_07_25_000000_create_love_reactant_reaction_counters_table.php
  database/migrations/2018_07_25_001000_create_love_reactant_reaction_totals_table.php
  src/Console/Commands/SetupReactable.php
  src/Console/Commands/SetupReacterable.php
  src/Support/Database/Migration.php
Labels: bugfix, enhancement

#121 Also drop foreign key before column
  src/Support/Database/Stubs/AddForeignColumn.stub
  src/Support/Database/Stubs/AddForeignNullableColumn.stub
Labels: bugfix
